name = mma
description = ...mma...
preview = preview.png
template = mma-layout

; Regions
regions[top_menu]		= Top Menu
regions[branding]       = Branding
regions[navigation]     = Navigation bar
regions[header]         = Header
regions[hero]           = Hero
regions[highlighted]    = Highlighted
regions[help]           = Help
regions[content]        = Content
regions[sidebar_first]  = First sidebar
regions[sidebar_second] = Second sidebar
regions[footer]         = Footer

; Stylesheets
stylesheets[all][] = css/layouts/mma/hero.layout.css
stylesheets[all][] = css/layouts/mma/hero.layout.no-query.css
